app: github-readme-svg
stage: dev
component: scf
name: github-readme-svg-scf
inputs:
  name: ${name}
  region: ap-shanghai
  runtime: Nodejs12.16
  src:
    src: ./dist
    exclude:
      - .env
      - package-lock.json
      - package.json
      - yarn.lock
      - README.md
      - node_modules
      - .eslintrc.js
  type: web
  handler: scf_bootstrap
  # installDependency: true
  # environment:
  #   variables:
  #     AppID: ${env:APP_ID}
  #     AppSecret: ${env:APP_SECRET}
  #     VerificationToken: ${env:VERIFICATION_TOKEN}
  #     EncryptKey: ${env:ENCRYPT_KEY}
  events:
    - apigw:
        parameters:
          protocols:
            - http
            - https
          environment: release
          endpoints:
            - path: /
              method: ANY
              # function:
              #   type: web
